### ISSUE TITLE
Need some sort of logging abstraction

### ISSUE THREAD

**Issue by dswisher** [cj525/Conduit.Net#1]
Using Console.WriteLine for logging is a tad suboptimal. There needs to be some sort of abstraction so that messages ("Unknown message in pipeline", for example) get picked up by whatever logger the host application is using.

**Comment by cj525** [comment]
This has been fixed by an abstract method in the Pipeline<T> base class:

https://github.com/cj525/Conduit.Net/blob/6e2a33e6c46c3036f38d00efaaf4bce04d48a206/src/Pipes/Abstraction/Pipeline.cs#L56

**Comment by cj525** [comment]
This has been fixed by an abstract method in the Pipeline base class:

https://github.com/cj525/Conduit.Net/blob/6e2a33e6c46c3036f38d00efaaf4bce04d48a206/src/Pipes/Abstraction/Pipeline.cs#L56
